---
- name: システムを更新
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: 必要なパッケージをインストール
  apt:
    name:
      - build-essential
      - curl
      - git
      - libssl-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - zlib1g-dev
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: GitHub CLI公式リポジトリを追加
  shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/github-cli.list

- name: パッケージリストを更新
  apt:
    update_cache: yes

- name: GitHub CLIをインストール
  apt:
    name: gh
    state: present 