---
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.docker
    version: ">=3.4.0"
  - name: community.crypto
    version: ">=2.14.0"

roles:
  - name: geerlingguy.docker
    version: ">=6.0.0"
  - name: geerlingguy.nodejs
    version: ">=8.0.0" 