name: 🐛 バグ報告
description: バグや不具合を報告する
title: "[Bug]: [問題の概要]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグ報告
        発見したバグや不具合について詳しく教えてください。

  - type: textarea
    id: bug_description
    attributes:
      label: 🐛 バグの説明
      description: 発生している問題を明確に説明してください
      placeholder: 例：チャットログ保存時にファイルが作成されない
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 🔄 再現手順
      description: バグを再現するための詳細な手順を記載してください
      placeholder: |
        1. スクリプトを実行: ./scripts/save-chat-log.sh
        2. ファイル名を入力: test-log
        3. エラーが発生する
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ 期待される動作
      description: 本来どのような動作をするべきかを説明してください
      placeholder: 例：chat-logs/ディレクトリにMarkdownファイルが作成される
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ 実際の動作
      description: 実際に発生している動作を説明してください
      placeholder: 例：エラーメッセージが表示され、ファイルが作成されない
    validations:
      required: true

  - type: textarea
    id: error_messages
    attributes:
      label: 📝 エラーメッセージ
      description: エラーメッセージやログがあれば貼り付けてください
      render: shell
      placeholder: |
        エラーメッセージをここに貼り付け

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 環境情報
      description: バグが発生している環境の詳細を記載してください
      placeholder: |
        - OS: Ubuntu 24.04 (WSL2)
        - シェル: bash 5.1.16
        - Git: 2.34.1
        - GitHub CLI: 2.40.1
        - Node.js: 23.8.0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🔥 重要度
      description: このバグの重要度を選択してください
      options:
        - 低 (軽微な問題)
        - 中 (機能に影響)
        - 高 (重要な機能が使用不可)
        - 緊急 (システム全体に影響)
    validations:
      required: true

  - type: checkboxes
    id: additional_info
    attributes:
      label: 📋 追加情報
      description: 該当する項目をチェックしてください
      options:
        - label: このバグは再現可能です
        - label: このバグは特定の条件下でのみ発生します
        - label: 回避策を見つけました
        - label: セキュリティに関連する可能性があります

  - type: textarea
    id: workaround
    attributes:
      label: 🔧 回避策
      description: 一時的な回避策があれば記載してください
      placeholder: 例：手動でファイルを作成することで対応可能

  - type: textarea
    id: additional_context
    attributes:
      label: 💡 追加のコンテキスト
      description: その他の関連情報があれば記載してください
      placeholder: スクリーンショット、関連するIssue、参考資料など