name: ✨ Enhancement Request
description: 既存機能の改善や新機能の提案
title: "[Enhancement] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能改善・追加のリクエスト
        既存機能の改善や新機能の提案をお聞かせください。

  - type: dropdown
    id: category
    attributes:
      label: カテゴリ
      description: どの分野の改善ですか？
      options:
        - Docker/インフラ最適化
        - MCP/AI機能強化
        - GitHub Actions/CI-CD改善
        - セキュリティ強化
        - パフォーマンス改善
        - ドキュメント整備
        - その他
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: 現在の状況
      description: 現在どのような問題や不便さがありますか？
      placeholder: |
        例: Docker起動時に〇〇が重い、MCPサーバーの設定が複雑など
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する改善案
      description: どのような改善を提案しますか？
      placeholder: |
        例: 
        - 自動停止機能の追加
        - 設定の簡素化
        - パフォーマンス監視機能
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この改善の緊急度は？
      options:
        - 🔥 緊急 (システム停止・セキュリティ)
        - ⚡ 高 (生産性大幅向上)
        - 📈 中 (便利な改善)
        - 📋 低 (あると良い)
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: 影響範囲
      description: この改善はどこに影響しますか？（複数選択可）
      options:
        - label: 🐳 Docker環境
        - label: 🤖 MCP/AI機能
        - label: ⚙️ GitHub Actions
        - label: 🔒 セキュリティ
        - label: 📊 パフォーマンス
        - label: 📚 ドキュメント

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他、参考になる情報があれば
      placeholder: |
        - 関連するファイルやスクリプト
        - 参考になるサイトやツール
        - 実装時の注意点など

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下を確認してください
      options:
        - label: 既存のIssueで同様の内容がないことを確認しました
          required: true
        - label: この改善が本当に必要であることを確認しました
          required: true