version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"  # File System MCP
      - "3001:3001"  # GitHub MCP
      - "3002:3002"  # Sequential Thinking MCP
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    command: npm run dev
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - mcp_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=mcp
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp_network

volumes:
  mongodb_data:

networks:
  mcp_network:
    driver: bridge 