---
- name: nvmをインストール
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm"

- name: nvmディレクトリを作成
  file:
    path: "{{ ansible_env.HOME }}/.nvm"
    state: directory
    mode: '0755'

- name: nvmの環境変数を設定
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    create: yes

- name: Node.jsをインストール
  shell: |
    source ~/.bashrc
    nvm install 23.8.0
    nvm use 23.8.0
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v23.8.0" 